#on:
#  push:
#    branches: master

on: push

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: nesto-toolchain:latest
          target: crosstool-ng_build-toolchain
          file: docker-crosstool-ng-arm/Dockerfile