on:
  push:
    paths:
      - 'src/**'
#    branches: master

env:
  STAGING_DIR: /usr/raspberry-build/staging
  SYSROOT: /opt/crosstool-ng/x-tools/arm-rpi-linux-gnueabihf/arm-rpi-linux-gnueabihf/sysroot
  ROOT_FS: /usr/raspberry-build/rootfs

jobs:
  build-app:
    name: Build usbproxy debian package
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/nesto-usbproxy-deps:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    steps:
    - name: Create build directory
      run: |
        mkdir -p src/build

    - name: Create Makefiles using CMake
      working-directory: src/build
      run: |
        LDFLAGS="-L${STAGING_DIR}/usr/local/lib" \
        CFLAGS="-I${STAGING_DIR}/usr/local/include" \
        CXXFLAGS=$CFLAGS \
        PKG_CONFIG_PATH=$STAGING_DIR/usr/local/lib/pkgconfig \
        cmake \
        "-DCMAKE_PREFIX_PATH=$STAGING_DIR/usr/local" \
        "-DCMAKE_FIND_ROOT_PATH=$STAGING_DIR" \
        "-DCMAKE_TOOLCHAIN_FILE=$TOOLCHAIN_FILE" \
        "-DCMAKE_INSTALL_PREFIX=/usr" \
        "-DCMAKE_BUILD_TYPE=Release" \
        "-DUSE_LIBUSB1=1" \
        ..

    - name: Run make
      working-directory: src/build
      run: |
        make

    - name: Run make install
      working-directory: src/build
      run: |
        DESTDIR=${ROOT_FS} make install

    - name: Build the debian package
      working-directory: src
      run: |
        dpkg-buildpackage -d -aarmhf -tarm-rpi-linux-gnueabihf

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: debian-package
        path: |
          *.deb